import { Injectable } from '@angular/core';
import { LanguageService } from './language.service';
import { SpiceService } from './spice.service';
import { SpiceLevel } from '../models/spice.type';

@Injectable({ providedIn: 'root' })
export class ChaiEngineService {
  constructor(
    private language: LanguageService,
    private spice: SpiceService
  ) {}

  private usedFacts = new Set<number>();

  // 🔹 ONLY the opening line changes with language
 private hinglishOpeners = [
  'Arre chhod na ye sab… ek spicy baat sun 👀',
  'Bhai ruk zara… ye wala sunega toh hass padega 😏',
  'Chal side rakh ye topic… asli scene bataun? 🔥',
  'Oye sun… ye baat thodi hatke hai 👂',
  'Arre ek second… ye ignore mat kar 😌',
  'Bhai trust me… ye interesting hai 👀',
  'Chhod drama… seedhi baat karta hoon 😎',
  'Ruk ruk… ispe tera reaction chahiye 😏',
  'Acha sun… ye thoda wild hai 🔥',
  'Bas ek line sun le… phir decide kar 😌',
];

private englishOpeners = [
  'Hold on… this one’s interesting 👀',
  'Wait a sec… you’ll like this 😏',
  'Pause everything… quick thought ☕',
  'Okay but listen to this 👂',
  'Before we move on… hear me out 😌',
  'Side note… this is too good to skip 👀',
  'Real quick… this caught my attention ☕',
  'Trust me for a second 😎',
  'One thing before that… 👀',
  'This deserves ten seconds of your time 😏',
];

  // 🔥 SPICE-BASED FACT POOLS
  private facts: Record<SpiceLevel, string[]> = {
    mild: [
      'Chai tastes better when someone else is paying.',
      'Indian families gossip the most right after saying “we don’t interfere.”',
      'Chai tastes better when someone else is paying, turning a simple roadside brew into a guilt-free symphony of spices that lingers on the tongue long after the last sip.',
'Indian families gossip the most right after swearing “we don’t interfere at all,” launching into marathon dissections of cousins’ lives over post-dinner chai sessions.',
'India reveres food as sacred from ancient Ayurvedic texts, yet samosas and jalebis were born when vendors smashed every diet rule in medieval bazaars for flavor rebellion.',
'Gujarat enforces ironclad prohibition laws statewide for decades, yet alcohol delivery apps there zip bottles to doors faster than pizza with ninja-level discretion.',
'Moms declare “we never interfere in your life choices,” then micromanage everything from grocery lists to marriage prospects via nonstop WhatsApp from continents away.',
'Varanasi pulses with unbroken human life for over 3,000 years, watching empires crumble while its Ganges ghats host the same rituals unchanged since antiquity.',
'India mined the world’s first diamonds from Golconda in 4th century BCE, quietly crowning European kings and funding lavish courts without seeking any credit.',
'Cows roam Delhi traffic as sacred VIPs because 3,500-year-old Vedic scriptures honor them as living mothers, blending faith with urban chaos seamlessly.',
'One in three Indians lives vegetarian lifelong from Jain-Hindu roots, making the nation Earth’s veggie powerhouse while secretly craving butter chicken on cheat days.',
'Snakes and Ladders started as 13th-century Moksha Patamu in India, teaching kids karma through sneaky gameplay centuries before Western board game knockoffs.',
'India rocketed to third globally in billionaires by 2025, birthing tycoons from chai-stall garages rather than Ivy League venture capital pipelines.',
'Hinduism endures as humanity’s oldest religion since 1500 BCE, outlasting pyramids with rituals and philosophies that never needed a single modern reboot.',
'India supplies 70% of global spices from Kerala’s misty hills alone, meaning your curry jar traces its fiery soul to soil older than most civilizations.',
'Ladakh’s Magnetic Hill fools cars into uphill rolls via optical slope illusions, baffling tourists for generations with nature’s cheeky gravity prank.',
'Roopkund Lake unveils 1,000-year-old skeletons each monsoon, capturing medieval pilgrims frozen by hailstorms in a Himalayan mystery still unsolved by DNA.',
'Young Indians call strangers “uncle-aunty” instantly, weaving familial warmth that turns airport small talk into surprise family reunions effortlessly.',
'Neighbor aunties greet as “didi-sister” with husbands as “bhaiya,” forging block-tight communities sans formalities or neighborhood association drama.',
'Northerners touch elders’ feet as casually as handshakes, a respect ritual so natural even tourists join in to unlock grandma’s secret recipes.',
'Chandrayaan-3 soft-landed moon’s south pole in 2023 on NASA’s fraction budget, scooping water ice secrets where richer agencies stumbled first.',
'India’s UPI handled more 2025 transactions than America’s full credit card empire, turning phone taps into frictionless money magic for all.',
'Every family’s election-oracle uncle nails polls better than pundits, proven by 2024’s twists that left exit polls blushing in embarrassment.',
'Moms hide veggies in dal with culinary stealth so perfect picky kids devour spinach unknowingly while swearing eternal green hatred.',
'Gandhi’s 1930 Salt March defied taxes and scripted non-violence blueprints that MLK copied for Selma, rewriting global freedom playbooks.',
'Penguins waddle Antarctic ice like aunties charging wedding buffets, proving nature bottled that relentless desi hustle energy perfectly.',
'Japan’s bullet trains quietly borrowed from India’s 2024 Vande Bharat speeds, blending Shinkansen sleekness with practical Indian commuter chaos.',
'Einstein binged chaat in 1922 India while debating relativity with Tagore, proving genius thrives on street spice over lab equations.',
'Family WiFi password hunts spark full democracies with votes, bribes, and alliances, training negotiation before civics class begins.',
'Ancient Indian spice trades bankrolled Europe’s Discovery Age, launching Columbus’s ships with pepper profits chasing richer horizons.',
'Dads treat veggie markets like gladiator arenas, haggling tomatoes to pennies with flair that humbles Wall Street dealmakers.',
'Post-2023 World Cup loss, families replay Rohit’s helicopter sixes endlessly, turning cricket heartbreak into sacred ritual lore.',
'Iceland’s hot springs envy Rishikesh Ganges yoga camps, where enlightenment flows cheaper and deeper than any Nordic spa.',
'Family “ghost auntie” spins Diwali firecracker fails as hauntings, scaring cousins straight for generations with embellished tales.',
'Kangaroos hop Australian plains like Indian kids fleeing homework, evolution favoring escape artists with boundless energy.',
'Power cuts birth candlelit family sagas outshining Netflix, bonding tighter through blackout tales than any binge session.',
'Bengaluru’s 2025 AI boom coded dreams over filter coffee, rivaling Silicon Valley with humid hustle over venture gloss.',
'One Indian shaadi’s gold outweighs Eiffel Tower steel, proving love’s extravagance defies engineering limits spectacularly.',
'Moms’ 2025 monsoon hunches beat apps via grandma knees, forecasting deluges with folklore sharper than satellites.',
'Vikings bartered ancient Indian ports for spices, blending fjord sagas with cardamom scents in unexpected fusion.',
'Grandma’s pickle recipes predate Republic India, fermented whispers guarding flavors no factory dare replicate.',
'90s aunties ran Barbie dramas with saree dolls before movies, staging matrimonial fashion shows in living rooms.',
'Egypt pyramids ramped like India’s ancient stepwells, engineering secrets swapped on early desert trade winds.',
'Neeraj Chopra’s 2024 javelin golds hurled Haryana grit onto Olympic gods, etching spears beyond mythic legends.',
'Penguins gift pebbles like mangalsutra exchanges, simple tokens sealing icy or mandap romances eternally.',
'90s photo albums burst with perm disasters uniting generations in laughter over shared fashion crimes.',
'Post-2023 WFH chai breaks boosted output richer than gadgets, turning calls into flavor-fueled focus sessions.',
'ISRO’s 2025 satellites blanketed India cheap, alerting droughts and pirates from space on chai budgets.',
'Monsoon pakoras spark antakshari wars, family voices clashing over storms in sizzling harmony.',
'Italy pasta wheat traces Silk Road Indian trades, carbs circling globe before Roman forks twirled.',
    ],
   medium: [
  'India pretends food is sacred, yet most snacks were invented by breaking all diet rules.',
  'Gujarat is officially dry, yet alcohol delivery there is shockingly efficient.',
  'Bollywood calls marriage sacred, yet 80% of A-list divorces hide secret casting couch deals from the 90s.',
  'Shah Rukh Khan preaches family man image, yet insiders whisper his late-night Dubai trips involve more than just business meetings.',
  'Deepika Padukone glows post-marriage, but Mumbai tabloids hint her Ranveer romance started as a PR stunt gone wildly real.',
  'Salman Khan swears off commitment forever, while whispers say he secretly funds multiple live-in girlfriends across three cities.',
  'Aishwarya Rai teaches elegance lessons, yet old crew members spill she once slapped a stylist over a bad hair day on set.',
  'Virat Kohli plays perfect husband PR, but IPL sources claim Anushka Sharma threw phones during 2024 World Cup loss rages.',
  'Priyanka Chopra sells global power couple vibes, yet Nick Jonas insiders say she controls his career picks like a Bollywood boss.',
  'Ranbir Kapoor promises fatherhood goals, yet Alia Bhatts friends hint he still texts exes during her pregnancy checkups.',
  'Katrina Kaif projects NRI sophistication, yet Vicky Kaushal admits their love sparked over drunk hookah sessions in London pubs.',
  'Aamir Khan lectures on social issues, yet PK set rumors say he had flings with three co-stars while preaching perfection.',
  'Modi ji vows clean politics, yet Delhi whispers link him to shadowy Gujarati diamond traders who fund election war chests.',
  'Rahul Gandhi poses as youth icon, yet family aides spill he parties harder in Bangkok than any Bollywood bachelor.',
  'Amit Shah masters iron-fist image, yet Karnataka leaks suggest his son’s tenders won via late-night ministerial calls.',
  'Arvind Kejriwal cries corruption tears, yet AAP insiders say his wife secretly owns half the party’s ad agency profits.',
  'Mamata Banerjee plays Didi savior, yet Bengal moles claim she buries opposition files under fake rape case distractions.',
  'Rohit Sharma captains with calm, yet Mumbai dressing room leaks say he smashed lockers after 2023 World Cup final choke.',
  'MS Dhoni stays mysterious yogi, yet Ranchi gossip ties him to underground betting rings from his IPL ownership days.',
  'Hardik Pandya flexes playboy vibes, yet Natasa Stankovic hints their split hid her discovering his three-city flings.',
  'Jasprit Bumrah dominates pitches, yet physio whispers say Sanjana Ganesan covers his steroid cycles with diet excuses.',
  'Suryakumar Yadav rises fast, yet IPL bookies claim his 2024 T20 form bought via spot-fixing side deals in Dubai.',
  'Gold hit 80k in 2025 Diwali, yet experts speculate RBI secretly dumps reserves to crash prices post-election.',
  'Silver surged 20% on Adani whispers, yet conspiracy circles say he cornered 40% supply via offshore Panama shells.',
  'Bitcoin crashed 50k mysteriously, yet Reddit sleuths tie it to Trump’s crypto wallet funding his 2026 re-election bid.',
  'Gold prices spiked post-2024 polls, but insiders hint Mamata hoarded 500 tons to bankrupt Bengal’s opposition.',
  'Diamond rates soared in Surat, yet Gujarat traders gossip Ambani secretly controls 70% via Africa blood mine routes.',
  'Nifty tanked 10% overnight, yet SEBI moles claim Adani-RBI nexus pumped fake retail trades to bail out debt.',
  'Crude oil futures manipulated, whispers say Saudi princes fund Bollywood starlets through UAE oil baron middlemen.',
  'Sensex rallied on green energy hype, but bears speculate Tata hoarded lithium mines to short rivals post-2025.',
  'Alia Bhatt’s baby rumors started early, yet crew says Ranbir pushed surrogacy to hide his fertility clinic visits.',
  'Kiara Advani shines bridal glow, yet Sidharth Malhotra insiders spill their shaadi fixed rival PR agencies’ feud.',
  'Nora Fatehi dances scandal-free now, yet P3G leaks say she bedded three politicians for visa extensions in 2023.',
  'Tiger Shroff stays single monk, yet gym sources claim Akshay Kumar hooked him up with Russian models quarterly.',
  'Karan Johar cries woke ally tears, yet Dharma insiders say he buries gay casting couch tapes in Swiss vaults.',
  'Ekta Kapoor rules TV soaps, yet Balaji moles whisper her brother Tusshar’s flings fuel 50% of plot inspirations.',
  'Hrithik Roshan flexes dad bod goals, yet ex-Saba spill he undergoes secret Botox parties in LA every quarter.',
  'Sunny Deol roars comeback king, yet Gadar 2 crew hints his temper tantrums cost 5cr in set rebuilds.',
  'Aditya Roy Kapur plays brooding hero, yet Ananya Panday friends say he ghosted her for rich NRI side pieces.',
  'Shraddha Kapoor screams innocent, yet Naagin set gossip ties her to black magic rituals for role extensions.',
  'Varun Dhawan promises family man, yet Natasha Dalal admits their honeymoon hid his boys-trip bachelor escapes.',
  'Yogi Adityanath enforces Hindutva iron, yet UP leaks claim his babas run cow smuggling to fund temple trusts.',
  'Stalin DMK preaches Dravidian pride, yet Tamil insiders say his son Udhayanidhi parties with starlets in Goa.',
  'Naveen Patnaik silent ruler, yet Odisha whispers tie his BJD to Chinese mining deals masked as green energy.',
  'Bhajan Lal Sharma Rajasthan strongman, yet Jaipur moles say his wife hoards mining leases via fake NGOs.',
  'Revanth Reddy Telangana reformer, yet Hyderabad leaks hint his farm laws hid corporate land grab payoffs.',
  'Rishabh Pant survives crash miracle, yet accident sleuths speculate drunk driving covered by BCCI hush money.',
  'KL Rahul bats steady hubby, yet Athiya Shetty sources say he resents Virat’s shadow in family PR wars.',
  'Shreyas Iyer IPL auction king, yet KKR insiders claim his form dips tie to late-night casino benders.',
  'Arshdeep Singh pace sensation, yet Punjab bookies whisper his no-balls fixed via Pak border betting syndicates.',
  'Ishan Kishan wicketkeeper prodigy, yet MI moles say his benching hid party drug tests gone wrong.',
  'Gold ETF inflows faked stats, conspiracy says banks launder black money through Diwali mutual fund rushes.',
  'Silver premiums hit record highs, yet MCX insiders speculate govt stockpiles for 2026 war chest builds.',
  'Crypto ban rumors spiked fear, but sleuths tie it to PMO wallets holding 10% of Indian Bitcoin mines.',
  'Stock options manipulated daily, whispers say Hindenburg planted fake shorts to crash Adani post-2025.',
  'Commodity futures rigged tight, yet Reddit claims Reliance cornered 60% gas via Gujarat port deals.',
  'Forex reserves dipped oddly, speculation points to Modi’s secret gold swaps with Russia amid sanctions.',
  'Ananya Panday acts star kid, yet Suhana Khan circle hints their friendship hides Aditya Roy love triangle.',
  'Janhvi Kapoor cries nepotism pain, yet Boney Kapoor spills she bedded directors for Sridevi sequel roles.',
  'Sara Ali Khan royal vibes, yet Saif insiders say her weight loss hid Ozempic addictions from shoots.',
  'Janvi Kapoor nepotism queen, yet friends spill she ghosted Shikhar Pahariya for richer NRI backups.',
  'Tara Sutaria bold new face, yet Aadar Jain family hints their split masked his drug rehab stints.',
  'Mrunal Thakur rising clean, yet Jersey crew whispers she traded intimacy for Telugu debut breakthroughs.',
  'Rashmika Mandanna pan-India darling, yet Animal set leaks say she begged Ranbir for intimate scene cuts.',
  'Nidhhi Agerwal South siren, yet iSmart Shankar moles claim her body double hid surgery scars.',
  'Poonam Pandey death hoax queen, yet insiders say it boosted her OnlyFans subs by 500% overnight.',
  'Urvashi Rautela Miss Universe glam, yet Rishabh Pant texts prove she leaked chats for revenge PR.',
  'Shehnaaz Gill Bigg Boss sweetheart, yet Sidharth Shukla circle hints her glow-up hides rehab visits.',
  'Elvish Yadav Bigg Boss bad boy, yet Haryana police whispers tie him to snake venom party rackets.',
  'Munawar Faruqui comedy king, yet ex-wife says his standup jokes hide domestic violence coverups.',
  'Abhishek Malhan YouTube sensation, yet Bigg Boss leaks claim he fixed votes via fan wallet bribes.',
  'Manisha Rani Bhojpuri fire, yet Jhalak moles whisper her dance moves learned in Patna underground clubs.',
  'Nitish Rana IPL captain cool, yet KKR bookies say his toss calls fixed via pre-match daddy meetings.',
  'Andre Russell power beast, yet West Indies rumors tie his form to TRT cycles hidden by KKR docs.',
  'Sunil Narine mystery spinner, yet Barbados leaks claim his batting switch flipped via betting coaches.',
  'Varun Chakravarthy leggie wizard, yet CSK insiders say his action modeled on Pak fixer side gigs.',
  'Rahul Tewatia finisher hero, yet GT moles whisper his cameos bought via Rajkot casino comps.',
  'Gold sovereign bonds flopped oddly, speculation says govt used them to siphon funds to poll bonds.',
  'Silver import duties hiked sneaky, yet traders gossip it protects Ambani’s solar panel silver hoard.',
  'Bitcoin halving rigged narrative, conspiracy ties it to Elon Musk’s India factory land grab deals.',
  'NSE co-location scam redux, whispers say SEBI chairs rotate via Hindenburg whistleblower payoffs.',
  'MCX gold options gamma squeeze, Reddit sleuths claim bank brass shorted retail on Diwali eve.',
  'RBI forex interventions masked, speculation points to rupee defense funding covert arms buys.',
  'Commodity MCX volumes faked, insiders say algo bots pump Ambani gas trades for FII inflows.',
  'Sensex derivatives expiry wild, bears speculate retail trapped in Tata Sons unlisted pumps.',
  'PSU bank NPA cleanups fake, leaks hint bad loans parked in Mauritius shells for 2026 polls.',
  'Adani airport bids fishy, conspiracy says green nod bought via green energy PR wash.',
  'Reliance Jio tariff hikes timed, whispers tie it to TRAI chair’s post-retirement board seat.',
  'Bharti Airtel 5G spectrum cheap, yet DoT moles claim Mukesh outbid Gautam via backroom calls.',
  'Vi bankruptcy drama scripted, speculation says Voda sold stakes to Adani at distress discounts.',
  'JioMart grocery wars brutal, insiders spill data sold to govt for citizen tracking apps.',
  'Nykaa IPO pumps questioned, whispers say Falguni Nayar’s Hurun list bought via ad spends.',
  'Zomato Blinkit acquisition hasty, Reddit claims Deepinder Goyal shorted Swiggy pre-deal.',
  'Paytm RBI bans suspicious, conspiracy ties it to Vijay Shekhar’s Congress funding U-turn.',
  'PhonePe Walmart exit drama, leaks say Banerjees cashed out to fund Karnataka poll machines.',
  'Groww mutual fund inflows fake, sleuths speculate demat hacks padded AUM for valuation pops.',
  'Angel One broking volumes juiced, insiders hint SEBI blind eye for Zerodha rivalry kills.',
  'Upstox shark fin trades, whispers say Ravi Adiga’s algos front-run retail on Nifty turns.',
  'Karan Taurani FY23 calls wrong, yet Motilal clients still pay for his Adani pump reports.',
  'Porinju Veliyath smallcap guru, yet Kerala leaks tie his picks to unlisted penny stock ramps.',
  'Dolly Khanna contra plays, speculation says Tamil Nadu agri funds laundered via her trades.',
  'Rakesh Jhunjhunwala legacy pumps, family whispers hold 20% Titan via offshore trusts.',
  'Ashish Kacholia midcap magic, insiders claim his de-listing deals net 5x unreported flips.',
  'Vijay Kedia steel bets bold, yet Jharkhand moles say his POSCO ties fund local polls.',
  'Mukul Agrawal pharma pumps, Reddit sleuths track his X posts to Twitter tip-off timings.',
  'Saurabh Mukherjea top 100 safe, yet Ambit clients gripe his funds trail Nifty by 10% yearly.',
  'Nirmal Jain IIFL gold loans, leaks hint NBFC evergreening via diamond collateral swaps.',
  'Sandip Sabharwal bear calls, whispers say he shorts Adani on Hindenburg tip-off calls.',
  'SP Tulsian midcap oracle, yet SEBI probes his chatroom pumps for 2024 delist binges.',
  'Gold ETF AUMs inflated sly, conspiracy claims black money recycles via festive SIPs.',
  'Silver futures contango wide, traders gossip MCX margins hiked to protect bank shorts.',
  'Bitcoin India ban lifted sneaky, speculation ties it to PMO crypto wallets for donor funds.',
  'Nifty bank index rigged expiry, insiders spill HDFC merger padded ICICI loan book optics.',
  'Rupee forward premiums spiked, RBI whispers mask oil import hedges for 2026 deficit.',
  'CRB commodity index faked, Reddit claims sugar ethanol blends launder cane baron cash.',
  'MCX crude volatility algo, leaks say Saudi Aramco pumps via Reliance trading desks.',
  'Sensex IPO pipeline juicy, bears speculate LIC follow-on diluted for poll bond buys.',
  'IRCTC railway stocks stable, yet station moles claim catering tenders fixed via Delhi.',
  'ONGC gas discoveries hushed, conspiracy says Adani ports grab export quotas first.',
  'NTPC green bonds greenwash, insiders hint coal plants relabeled for ESG fund inflows.',
  'Coal India auction losses, whispers tie pitheads to Yogi’s UP temple land swaps.',
  'SAIL steel import duties safe, yet JPC moles say China dumps routed via Vietnam.',
  'NMDC iron ore premiums high, speculation claims Telangana mines fund Revanth PAC.',
  'Hindalco aluminum LME beats, Reddit sleuths track Birla London trades to election timing.',
  'Tata Steel Europe losses cut, insiders spill UK unions bought off via JRD trusts.',
  'JSW infra port bids won easy, leaks hint Goa mining leases collateral for loans.',
  'Vedanta oil blocks revoked drama, conspiracy says Anil Agarwal lobbies via London courts.',
  'HPCL refinery margins fat, yet BPCL moles claim IOC price war fixed by oil ministry.',
  'BPCL Alaska bid pulled odd, whispers say Rosneft JV hid Putin-Modi arms offsets.',
  'IOC petrol pricing delayed, speculation ties diesel subsidy to farmer vote banks.',
  'GAIL PNG tariffs hiked quiet, insiders spill city gas arms laundered via realty.',
  'Indraprastha Gas Delhi monopoly, Reddit claims Adani entry blocked by Kejriwal donors.',
  'Mahanagar Gas Mumbai pipes, leaks say BG Group stakes parked in Mauritius for flips.',
  'Gold loan NBFCs NPA spike, conspiracy hints Muthoot-Manjunath evergreened via weddings.',
  'PNB Housing loan book clean, yet Yes Bank style fraud hid in co-lender pools.',
  'Bajaj Finserv lending boom, whispers claim NBFC arms fund electoral bonds slyly.',
  'Shriram Finance rural gold, insiders spill microloan sharks collect via goon squads.',
  'Cholamandalam vehicle loans, Reddit sleuths track repo rates to Ambani car sales.',
  'LIC Housing cheap home loans, leaks hint policyholder funds parked in infra bonds.',
  'SBI Cards credit limits cut, speculation says retail debt fuels SME poll packages.',
  'HDFC Bank merger synergies fake, moles claim ICICI rivalry padded NPA provisions.',
  'Kotak Mahindra alt investments, whispers tie family office to Panama crypto plays.',
  'Axis Bank slab deals fishy, insiders spill slab parking for Vijay Mallya extradition.',
  'IndusInd Hinduja NRI loans, conspiracy claims UAE remittances laundered via FDs.',
  'Federal Bank Kerala gold rush, leaks say Malabar black money recycles via vaults.',
],
kadak :[
  
    'Societies that scream “sanskar” the loudest often run the most secret WhatsApp groups tracking Bollywood stars’ casting couch trades with underworld dons like Dawood Ibrahim.',
    'Victorian England banned public affection while quietly funding entire pleasure districts staffed by Indian courtesans shipped via East India Company ships for elite orgies.',
    'Shakti Kapoor got caught on sting camera offering sex for roles, bragging Aishwarya Rai and Riya Sen bedded producers like Subhash Ghai to climb the ladder.',
    'Bipasha Basu\'s affair with Amar Singh leaked via Panama Papers, tying her to political honeytraps that fixed Bollywood deals and election favors in hotel suites.',
    'Mandakini\'s Dawood Ibrahim bedroom romps surfaced in 90s whispers, her Underwear ads masking trips to Dubai where gangsters scripted her scripts and her screams.',
    'Riya Sen\'s porn video circulated black market, filmed during a coke-fueled party where Telugu politicians took turns directing her debut degradation.',
    'Shamita Shetty\'s nude pics hit net from hacked phone, insiders say snapped during London threesomes with Pakistani cricketers dodging match-fixing probes.',
    'Aryan Khan\'s drug bust hid bigger Sushant Singh Rajput murder links, CBI buried files showing Bollywood pedo rings funded by Adani cash via Malta banks.',
    'South politician KTR tapped Rakul Preet and Samantha phones for blackmail tapes, demanding bedroom videos or their films get banned post-election.',
    'Tanushree Dutta exposed Nana Patekar\'s car grope turning into forced oral on 2008 set, #MeToo tip of iceberg where 70% heroines paid with flesh for hits.',
    'Sanjay Dutt\'s arms case masked Dawood-supplied AK-47s used in Mumbai blasts, Juhu parties where starlets snorted lines off gangster thighs.',
    'Indira Gandhi allegedly ordered Sanjay\'s assassination via LTTE precursors, Congress black money in Singapore funded Rajiv\'s killers for power grabs.',
    'Kapil Dev cozied to Dawood for match-fixing millions, Tehelka sting caught Sunil Gavaskar admitting World Cup 1983 bribes rigged Aussie umpires.',
    'Wasim Akram\'s no-balls scripted by bookies in Lahore whorehouses, Inzamam ul-Haq blew fixing cash on heroin hookers in Dubai penthouses.',
    'Russell Brand propositioned hotel staff for threesomes, offering hubby inclusion while Keanu Reeves grabbed Renee Zellweger\'s boobs wiring mics for NSFW fun.',
    'Matthew Gray Gubler leashed girlfriend publicly on Insta, BDSM collar snaps sparking Criminal Minds smut fics where Reid dominates subs savagely.',
    'Bollywood-underworld nexus exploded with Gulshan Kumar\'s 1997 assassination, producers paying protection via starlet virgins offered to Abu Salem.',
    'Ranbir Kapoor leaked Katrina Ibiza bikini pics for revenge porn, same hand behind Mahira Khan\'s smoking scandal to tank her Pak career.',
    'Amitabh Bachchan\'s Rekha affair scorched screens, secret lovechild rumors buried under ABCL slush funds from Bofors scandal payoffs.',
    'Sharad Pawar bankrolled by Dawood via Telugu scam, Chhagan Bhujbal laundered Mumbai underworld cash through NCP election coffers.',
    'Manipur crisis hides ethnic cleansing camps where militants rape cadres nightly, Reasi attacks funded by ISI porkis smuggling arms via Naga tunnels.',
    'Naxal Chhattisgarh villages burn with kids beheaded, illegal Rohingya migrants get Aadhaar-fake docs for jihad sleeper cells in Delhi slums.',
    'Hardik Pandya\'s Natasa split exposed Mumbai hotel tapes of him railing escorts while she filmed OnlyFans revenge nudes leaked anonymously.',
    'MS Dhoni\'s yogi mask cracks with Ranchi betting dens where IPL wives swap husbands during victory parties laced with Viagra and coke.',
    'KL Rahul resents Virat\'s glow, Athiya Shetty catches him sexting IPL cheerleaders in team bus blackouts.',
    'Rishabh Pant crash staged to cover drunk orgy with minor models, BCCI payoffs silenced cops probing semen-stained wreckage.',
    'Sunil Narine\'s batting flip hides Pak bookie bribes, Barbados dens where he snorted lines off trans hookers post-fixing.',
    'Kulbhushan Jadhav spy op sparked Chaudhry Aslam hit, Indian RAW runs Lyari gang wars arming Baloch sex slaves against Pak ISI.',
    'Hamid Mir podcast spills RAW honeytraps in Karachi brothels, ISI counters with acid attacks on captured agents\' families.',
    'Sushant Rajput suicide faked, Disha Salian tossed from building after filmed gangbanged by Bihar politicians in Mumbai flat.',
    'Nirav Modi fled with PNB 14k cr scam funded by Nirbhaya convict lawyers, diamonds cut from raped girls\' jewelry smuggled to Antwerp.',
    'Vikas Dubey UP encounter king executed 8 cops, Yogi buried his STF dalliances with minor brides bought from Bhopal trafficking rings.',
    'Sheena Bora murder by Indrani hid Parsi incest tapes, Chikki Podar supplied coke to Mumbai elite pedo parties.',
    'Telgi stamp paper scam printed fake notes for Dawood hawala, Abdul Karim Telgi bedded IAS wives for tender leaks.',
    'Harshad Mehta bull run crashed markets with SEBI bribes, suicide staged to cover Dubai escape with 500cr in Swiss hooker accounts.',
    'NSEL scam Vijay Kedia pumped onion futures, warehouses stuffed with adulterated spice laced for Mumbai rave poisonings.',
    'IL&FS debt bomb 91k cr defaulted on chit fund ponzis, DW Goenka ran Orissa sex farms supplying minors to Delhi ministers.',
    'Yes Bank Rana Kapoor lent to DHFL wala, Kapil Wadhawan laundered via Kapoor daughters\' Dubai lingerie empire.',
    'Lakshmi Vilas merger hid LVB NPA from Karur church sex scandals, bishops pimped nuns for loan waivers.',
    'Punjab National Bank Nirav loot via SWIFT hacks, Mehul Choksi fled to Antigua with Antiguan teen brides on yacht.',
    'PMC Bank 9k cr rot hid Shiv Sena builder suicides, Yuvraj Patil overdosed on hooker fentanyl in Oshiwara flat.',
    'DHFL 34k cr IBC mess, Dheeraj Wadhawan taped blackmailing RBI with Mumbai club toilet cams.',
    'Jet Airways Naresh Goyal jetset bankrupt, Anita Goyal hawked jewelry to fund London coke parties for pilots.',
    'Kingfisher Vijay Mallya UB liquor heir fled 9k cr, Aussie models testified to yacht orgies with forced NDAs.',
    'Gitanjali Gems Mehul Choksi PNB diamond dupe, Zaveri Bazaar rats say he melted raped jewelry into scam stones.',
    'Adani-Hindenburg short attack buried SEBI probes, Gautam\'s ports ship Chinese fentanyl subs to Manipur militants.',
    'Reliance Jio 5G towers spy cams hack Aadhaar, Mukesh Ambani sells celeb nudes to ISI for Kashmir land deals.',
    'Tata Sons Cyrus Mistry crash hid Singapore slush for Nano flop bribes to Bengal farmers evicted naked.',
    'Bharti Airtel Sunil Mittal spectrum 2G scam survivor, raided for Ukrainian arms routed via 5G towers.',
    'Wipro Azim Premji IT visas fake H1B sex trafficking, Bangladeshi coders pimped to Cali tech brothels.',
    'HCL Shiv Nadar Noida campus sweatshops, Chinese spies embedded coding RAW dossiers for Beijing handover.',
    'Infosys Narayana Murthy ethics preach, SDLC whistleblower Soni Sood suicided after taped boardroom rape.',
    'TCS TCS N Chandrasekaran Tata trust loot, cyber slaves in Kochi call centers dialing sextortion for Triad.',
    'L&T Kumar Mangalam Birla infra bids rigged, Delhi Metro tunnels hide Dawood arms dumps for 26/11 sequel.',
    'JSW Sajjan Jindal steel rapes in Bellary mines, tribal girls chained for Karnataka poll vote orgies.',
    'Vedanta Anil Agarwal Zambia copper kids labor, Congo militias supply conflict coltan fucked from child wombs.',
    'UltraTech Aditya Birla cement dust kills Bihar villages, poisoned wells laced with Bhopal gas runoff.',
    'Apollo Hospitals Prathap Reddy organ harvest ring, road accident vics chopped for Saudi sheikh transplants.',
    'Fortis Malvinder Singh DHFL debt slaves, Gurgaon basement BDSM for Chinese loan shark collectors.',
    'Max Healthcare Abhay Soi elective surgeries fake, Covid ventilators wired to harvest adrenochrome from kids.',
    'Narayana Health Shetty model cheap deaths, Karnataka hostels cram Covid corpses for oxygen black market.',
    'Manipal Devi Shetty NRI kidneys trade, Gulf expats buy Indian poor organs via fake tourist visas.',
    'Kerala Blasters Nivin Pauly football fixes, Kochi flood bodies dumped to hide player doping autopsies.',
    'RCB Virat Kohli jersey sales launder, Bangalore bookies bet on his bedroom stamina with star wives.',
    'CSK Dhoni CSK betting syndicate, Chennai Super Kings crown hides Super Kings of vice lords.',
    'MI Rohit Ambani payroll prince, Wankhede suites host cocaine cricket afterparties with models.',
    'PBKS Preity Zinta Punjab party pads, Mohali mansions echo with raped fans silenced by NDAs.',
    'RR Shane Warne ghost doping cartel, Jaipur palaces pump steroids from Pakistani labs.',
    'KKR Shah Rukh Kolkata knight underworld, Eden Gardens tunnels smuggle heroine for Tollywood.',
    'DC Shreyas Iyer Delhi daredevil drugs, Arun Jaitley stadium stashes coke for VIP boxes.',
    'GT Hardik Pandya Gujarat glitz gangbang, Narendra Modi stadium echoes with cheerleader screams.',
    'LSG KL Rahul Lucknow love triangle leaks, Ekana tapes catch him railing opposition WAGs.',
    'SRH Pat Cummins Sunrisers steroids, Hyderabad pharma pumps Aussie veins for orange cap.',
    'Trump reelection rigged Epstein files, Lolita Express logs show Modi guested island pedo parties.',
    'Biden laptop Hunter crack child vids, Ukraine biolabs breed Wuhan superspreaders shipped to India.',
    'Macron Brigitte trans op funded Rothschild, Élysée threesomes with migrant traffickers.',
    'Netanyahu Mossad Epstein handler, Gaza tunnels hide Tel Aviv sex slave auctions.',
    'Xi Jinping daughter Harvard whorehouse, Peng Lifa bridge suicide faked after PLA rape tapes.',
    'Putin Wagner Prigozhin plane bomb, Africa cobalt mines fuck child slaves for EV batteries.',
    'Kim Jong Un Tokyo assassin honeytraps, Abe funeral hid bullet from North Korean viagra overdose.',
    'Modi Rafale Dassault kickbacks, Anil Ambani offset factories build Sushant murder drones.',
    'KeJri AAP Delhi liquor scam hooch deaths, Arvind\'s wife bottles laced with fentanyl for rivals.',
    'Mamata Bengal doctor rape coverup, Sandeshkhali camps chain Hindu girls for Rohingya jihadis.',
    'Stalin Tamil Nadu Kallakudi riots fake, DK Shiavakumar mines fund LTTE revival arms.',
    'Bhupesh Baghel Chhattisgarh Maoist porn, Bastar videos show cadres raping surrendered cadres.',
    'Gold mafia Antwerp Indian diamonds blood, Surat polishers grind Congo child fingers into gems.',
    'Pakistan ISI Hafiz Saeed Mumbai handler, 26/11 Ishrat Jahan bedroom bait for RAW moles.',
    'China RAW sleeper Wang Liqiang defect, Tibet camps harvest Falun Gong organs for PLA generals.',
    'US DIA Vindman Ukraine coup porn, Zelenskyy Zelensky tapes sold to Burisma gas oligarchs.',
    'UK MI6 Boris parties PPE scam bodies, Hancock hid care home murders for Gates vaccine trials.',
    'France DGSE Macron coke dwarf orgies, Brigitte cage kink leaked from Élysée dungeon cams.',
    'Germany BND Merkel migrant rape gangs, Cologne NYE covered by Soros NGO payoffs.',
    'Canada CSIS Trudeau blackface SNC bribes, ArriveCan app hacks harvest refugee nudes.',
    'Australia ASIO Morrison bushfire pedo rings, ScoMo church hid altar boy tapes for votes.',
    'RAW Kulbhushan Baloch sex farms, Jadhav ran Karachi brothels torturing Pak officers\' daughters.',
    'ISI RAW double agent Rabinder Singh fled, honeytrap vids show him railing Delhi airhostesses for CIA.',
    'CBI Neeraj Grover murder Maria Susairaj chopped, Kollywood cannibal kitchen fed starlets.',
    'NIA JNU Umar Khalid ISIS groomer, campus cunts converted via burqa basement rapes.',
    'ED P Chidambaram INX 2G whore ledger, Kanimozhi bedded A Raja for spectrum allotments.',
    'CBI Aarushi Talwar parents orgy killers, Nithari canal bodies from DGP uncle parties.',
    'Nirav Modi Gitanjali ratan tata blackmail, Cyrus crash hid Nano child labor camps.',
    'Vijay Mallya Kingfisher calendars nude models minors, UB liquor spiked with date rape.',
    'Nirbhaya bus Jyoti Singh gutted alive, Mukesh Singh brothers bragged intestines necklace.',
    'Jessica Lal murder Manu Sharma club shot, Sheila Dixit daughter covered drunk MP rampage.',
    'Priyadarshini Mattoo Santosh Kumar acid raped, Delhi HC freed him for Delhi HC judge honey.',
    'BPO call girl Scarlett Keeling Goa beach drowned, Fiona Mackeown pimped to Russian mafia.',
    'Lal Bihari fake death voter scam, Azamgarh zombies vote Congress via graveyard bribes.',
    'Vyapam scam 2k dead witnesses, Shivraj Singh Chouhan STF silenced via monkeypox fakes.',
    'Sterlite Tuticorin firing 13 dead, Vedanta copper fumes sterilized Tamil Nadu wombs.',
    'Jallikattu bulls spiked steroids rape, PETA vids show doped beasts mounting trainers.',
    'Kumbh Mela 36 drowned stampede, Akhilesh Yadav stage collapse hid illicit liquor flood.',
    'Mumbai stampede Elphinstone 23 crushed, BMC bribes skipped escalator safety gates.',
    'Bengaluru stadium collapse 2014, Karunadu Jagruti Vedike rally crushed kids for votes.',
    'Hathras Dalit girl raped parade corpse, UP cops cremated body to bury UP MLA semen.',
    'Unnao rape MLA Kuldeep Sengar sister shot, CBI hid acid attack on victim family.',
    'Kathua 8yo Bakr Eid goat fuck ritual, BJP lawyers defended temple rapists publicly.',
    'Hyderabad vet Disha torch naked, Telangana cops staged encounter after gang anal vids leaked.',
    'Vadodara twins incest parents jail, Gujarat incest farm bred for NRI porn exports.',
    'Kolkata RG Kar doctor rape throat slit, Mamata CBI blocked SFI hostel gangbang probe.',
    'Srinagar Handwara militant beheaded CRPF, Burhan Wani vids show jawans castrated alive.',
    'Pulwama 40 jawans bus bombed, Jaish IEDs laced with Pakistan army officer pubes.',
    'Balakot airstrike F16 downed hidden, Abhinandan tea with Pak air chief torture tapes.',
    'Surgical strike Uri faked casualties, RAW staged Pathankot airbase drone semen bombs.',
    'Galwan 20 soldiers bludgeoned, Xi Jinping PLA filmed beheadings for Beijing kink clubs.',
    'Beijing 2022 Olympics Peng Shuai raped, IOC Samaranch covered state orgy with gymnasts.',
    'Wuhan lab leak Fauci funded gain-function, Daszak bat soup spiked HIV for population cull.',
    'Pfizer vax trials kids paralyzed microchips, Bill Gates RFID jabs track Indian poor.',
    'WHO Tedros Ethiopia Tigray famine porn, Abiy Ahmed camps starve Christians for UN funds.',
    'UNICEF Gaza tunnels pedo playgrounds, Hamas rockets tipped with Israeli settler foreskins.',
    'Epstein island Modi guested Lolita flight, Maxwell procured teen virgins for Davos deals.',
    'Weinstein Miramax rape room Hollywood, Harvey fed Viagra crushed in champagne to starlets.',
    'R Kelly piss dungeon Chicago, Aaliyah underage marriage hid abortion at 15.',
    'Rolf Harris didgeridoo dildo kids TV, Aussie BBQs grilled pedo sausage with vegemite.',
    'Jimmy Savile BBC corpse fucking graves, Thatcher hid hospital ward boy buggery.'
  ]
  };

  getReply(userInput: string): string {
    const opener = this.language.isHinglish()
      ? this.pickRandom(this.hinglishOpeners)
      : this.pickRandom(this.englishOpeners);

    const fact = this.pickUnusedFact();
    return `${opener}\n\n${fact}`;
  }

  private pickRandom(arr: string[]): string {
    return arr[Math.floor(Math.random() * arr.length)];
  }

  private pickUnusedFact(): string {
    const level = this.spice.getLevel();
    const pool = this.facts[level];

    if (this.usedFacts.size === pool.length) {
      this.usedFacts.clear();
    }

    let index: number;
    do {
      index = Math.floor(Math.random() * pool.length);
    } while (this.usedFacts.has(index));

    this.usedFacts.add(index);
    return pool[index];
  }
}
